
GEMINI_KEYS = ["AIzaSyDZVaoTKys0yK_NOyT974zcOEeD8Nso380",
  "AIzaSyAmZS9zsJbCfGSRaVQD-l6l3SEiJRjFuJE",
  "AIzaSyDzQg74lBv-dUEsp3w0mleO1CgHZka9wMM",
  "AIzaSyBwFga_SY-xbKThlO193PqMM9tWopZnVeY",
  "IzaSyBBtULAeh20bxv_qZyni3P2cninVDHXPJw"
]
